### ISSUE TITLE
functions deploy helloWorld fails with 'Error: Cannot read property '1''

### ISSUE THREAD

**Issue by olegwn** [GoogleCloudPlatform/cloud-functions-emulator#100]
### Description

When I try to deploy a simple app helloWorld from documentation with command:

`functions deploy helloWorld --trigger-http`

 I get error:

ERROR: Error: Cannot read property '1' of null
    at Request._callback (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/google-auth-library/lib/transporters.js:101:13)
    at Request.self.callback (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

### Additional info

Upon digging I found that deploy command gets 500 Internal Server Error in `google-auth-library/lib/transporters.js`

### My Config

functions emulator version: 1.0.0-alpha.17
OS: Mac OS X 10.12.4
Node version: v6.9.1
Python version: 2.7.10

**Comment by jmdobry** [comment]
What directory are you running the deploy command in?

**Comment by olegwn** [comment]
@jmdobry from root of the project or from functions directory, doesn't matter, still get this error

**Comment by jmdobry** [comment]
Can you provide me with some exact reproduction steps? e.g. installing and starting the emulator, source code of the function, deploying the function, etc.

**Comment by MrMaxRoss** [comment]
Same issue here.

I'm just following the installation and deploy steps described on this page:
https://cloud.google.com/functions/docs/emulator

My function is just the function from the Quickstart:
```
exports.helloWorld = function helloWorld (event, callback) {
  console.log(`My Cloud Function: ${event.data.message}`);
  callback();
};
```
functions emulator version: 1.0.0-alpha.18
OS: Mac OS X 10.12.4
Node version: v6.9.1

**Comment by MrMaxRoss** [comment]
Looks like user error, sorry.

I was invoking functions deploy with the name of the file containing my function, not the function name. When provided the function name rather than the filename the deploy was successful.

The emulator should probably return a helpful error message when it doesn't recognize the name of the function that the user is trying to deploy.

**Comment by jmdobry** [comment]
Hmm, I was unable to reproduce. Here is what I have:

functions emulator version: 1.0.0-alpha.18
OS: Mac OS X 10.12.4
Node version: v6.9.1
npm version: v3.10.8

And the steps I used to reproduce:

1. `npm uninstall -g @google-cloud/functions-emulator`
1.  `npm install -g @google-cloud/functions-emulator`
1.  `functions start`

    Which yielded:

        Starting Google Cloud Functions Emulator...
        Google Cloud Functions Emulator STARTED
        No functions deployed ¯\_(ツ)_/¯. Run functions deploy --help for how to deploy a function.

1.  `mkdir helloWorld`
1.  `cd helloWorld`
1.  `touch index.js`
1.  `echo 'exports.helloWorld = (req, res) => res.send("Hello, World!");' > index.js`
1.  `functions deploy helloWorld --trigger-http`

    Which yielded:

        Copying file:///var/folders/jm/wt5pk0d1641bjbc4mt5pz6r800_933/T/us-central1-helloWorld-7017BAvOAYusSt6h.zip...
        Waiting for operation to finish...done.
        Deploying function......done.
        Function helloWorld deployed.
        ┌────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────┐
        │ Property   │ Value                                                                                               │
        ├────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────┤
        │ Name       │ helloWorld                                                                                          │
        ├────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────┤
        │ Trigger    │ HTTP                                                                                                │
        ├────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────┤
        │ Resource   │ http://localhost:8010/nodejs-docs-samples/us-central1/helloWorld                                    │
        ├────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────┤
        │ Timeout    │ 60 seconds                                                                                          │
        ├────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────┤
        │ Local path │ /Users/jdobry/projects/nodejs-docs-samples/helloWorld                                               │
        ├────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────┤
        │ Archive    │ file:///var/folders/jm/wt5pk0d1641bjbc4mt5pz6r800_933/T/us-central1-helloWorld-7017BAvOAYusSt6h.zip │
        └────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────┘

1.  `curl http://localhost:8010/nodejs-docs-samples/us-central1/helloWorld`

    Which yielded:

        Hello, world!


What am I missing?

**Comment by olegwn** [comment]
@jmdobry just followed exactly your steps from 1 to 8 and step 8 yielded:

functions deploy helloWorld --trigger-http

`ERROR: Error: Cannot read property '1' of null`

very strange :-(

**Comment by jmdobry** [comment]
Can you try the following:

```
functions config set service grpc
functions restart
functions deploy helloWorld --trigger-http
```

**Comment by olegwn** [comment]
@jmdobry 

I tried as you suggested and I got same error but with different stack trace:

    $ functions deploy helloWorld --trigger-http
    ERROR: Error: Cannot read property '1' of null at /usr/local/lib/node_modules/@google-cloud/functions-
    emulator/node_modules/grpc/src/node/src/client.js:434:17

**Comment by jmdobry** [comment]
I'm stumped :/

**Comment by jmdobry** [comment]
@MrMaxRoss If you attempted to deploy a function that couldn't be found in the file, then you should have seen an error like this per [src/cli/controller.js#130](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/blob/master/src/cli/controller.js#L130):

```
ERROR: Function load error: Code could not be loaded.
ERROR: Does the file exist? Is there a syntax error in your code?
ERROR Detailed stack trace: ...
```

Did you not see that? If so can you open a different issue with expected vs actual behavior and reproduction steps?

**Comment by olegwn** [comment]
@jmdobry me too. Maybe it's my environment, i will try on another computer with similar setup and let you know

**Comment by olegwn** [comment]
@jmdobry works fine on my other Mac OS X machine , very strange, must be something in the environment, i'll let you know when i find what caused this error

**Comment by olegwn** [comment]
@jmdobry weird stuff, i managed to make it work just by doing this command

`functions config set projectId %myProjectId%`

and now everything just works (grpc or rest, both) ¯\_(ツ)_/¯

**Comment by jmdobry** [comment]
Hmm, if you didn't have a project ID set, it should have been prompting you to set one...

**Comment by warnerpinz** [comment]
I followed the EXACT steps from @jmdobry and I get this response when doing cURL:

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /</pre>
</body>
</html>
