### ISSUE TITLE
Cannot install functions-emulator with npm

### ISSUE THREAD

**Issue by robbiexperiel** [GoogleCloudPlatform/cloud-functions-emulator#106]
### Description

`npm install -g @google-cloud/functions-emulator` fails with the following message:
```
npm ERR! git clone git@github.com:google-cloud/functions-emulator undefined
npm ERR! git clone git@github.com:google-cloud/functions-emulator undefined
npm ERR! addLocal Could not install google-cloud/functions-emulator
npm ERR! Error: ENOENT, stat 'google-cloud/functions-emulator'
```

### Steps to reproduce

1.  `npm install -g @google-cloud/functions-emulator`

That was run in a docker debian:latest image with npm installed.

Thanks!

**Comment by jmdobry** [comment]
That error leads me to believe that the image had a version of npm installed that's too old. Older versions of npm don't understand scoped packages that contain `@` in the name.

**Comment by robbiexperiel** [comment]
You're right, the docker image was based on Debian Jessie, which seems to have a 3 year old version nodejs in its repos. Thanks!
