### ISSUE TITLE
npm install command not working

### ISSUE THREAD

**Issue by FlavouredDavid** [GoogleCloudPlatform/cloud-functions-emulator#114]
### Description

When running the recommended npm install command `npm install -g @google-cloud/functions-emulator` I get the following error:

```
npm ERR! git clone git@github.com:google-cloud/functions-emulator Cloning into bare repository '/home/flavoureddavid/.npm/_git-remotes/git-github-com-google-cloud-functions-emulator-8c2e1754'...
npm ERR! git clone git@github.com:google-cloud/functions-emulator ERROR: Repository not found.
npm ERR! git clone git@github.com:google-cloud/functions-emulator fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:google-cloud/functions-emulator 
npm ERR! git clone git@github.com:google-cloud/functions-emulator Please make sure you have the correct access rights
npm ERR! git clone git@github.com:google-cloud/functions-emulator and the repository exists.
npm ERR! addLocal Could not install google-cloud/functions-emulator
npm ERR! Error: ENOENT: no such file or directory, stat 'google-cloud/functions-emulator'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
```

Note: this also occurs when running with `sudo`.  Looks like the repo has been moved but the npm info hasn't been updated.  Thanks.

### Steps to reproduce

Run the command: `npm install -g @google-cloud/functions-emulator`

### System

OS: Linux

Thanks!

**Comment by jmdobry** [comment]
You should not need to use `sudo` to install or run the Emulator, doing so indicates a problem with your Node.js installation. My recommendation is to wipe all trace of Node.js/npm from your system and re-install Node.js/npm using [nvm (Node Version Manager)](https://github.com/creationix/nvm).

For more information, see [Installing the Emulator](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Installation).
