### ISSUE TITLE
invalid JSON format error

### ISSUE THREAD

**Issue by cliquot22** [GoogleCloudPlatform/cloud-functions-emulator#117]
### Description

I'm following the example and trying to send JSON data to my function.  Even with the helloWorld function I'm getting an error: "data" must be a valid JSON string!
I copied it directly from the help and it looks valid.  What's the issue? I'm running on Windows10

### Steps to reproduce

functions call helloWorld --data={"foo":"bar"}

Thanks!

**Comment by cliquot22** [comment]
I discovered you have to escape the quotes in the json string: 
functions call helloWorld --data={\"foo\":\"bar\"}

That works

**Comment by jmdobry** [comment]
Yes, on Windows you have to escape the quotes. See [Calling Functions](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Calling-functions) for Windows examples.
