### ISSUE TITLE
function failed to deploy

### ISSUE THREAD

**Issue by kpr6** [GoogleCloudPlatform/cloud-functions-emulator#118]
Gives out this error:

```
2017-06-14T19:01:20.954Z - error:  RequestError: socket hang up
    at ClientRequest.req.once.err (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/got/index.js:105:21)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketOnEnd (_http_client.js:394:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Using node v6.11.0. Can you please help

**Comment by cliquot22** [comment]
What does your code look like?  When I get the "failed to deploy" error i usually have a syntax error in my function.  Try looking at line 21 in your code.

**Comment by kpr6** [comment]
exports.dataflow1 = function (event, callback) {
  const file = event.data;
  const spawn = require('child_process').spawn;

  if (file.resourceState === 'not_exists') {
    console.log(`File ${file.name} deleted.`);
  } else if (file.metageneration === 1) {
    
    console.log(`File ${file.name} uploaded.`);
  } else {

        const child = spawn(
            'jre/bin/java',
            ['-jar',
             'newDataflow-bundled-0.0.1-SNAPSHOT.jar',
             '--project = rwa-tooling',
             '--inputFile="gs://cdw-data/CUSTOMER_CDW_V1_20170107.csv" ',
             '--tableName="rwa-tooling:ZZZ_Team_Sandbox_Dataset.CDW_CUSTOMER2$20170107" ',
             '--columns="gs://rwa_bucket1/columns.txt" ',
             '--schema="gs://cdw-data/CUSTOMER_CDW_schema.txt" '
            ],
            { cwd: __dirname });

    child.stdout.on('data', function(data) {
        console.log('stdout: ' + data);
        event.success("Success: " + data);      
    });

    child.stderr.on('data', function(data) {
        console.error('error: ' + data);
        event.failure("Error: " + data);
    });

    child.on('close', function(code) {
        console.log('closing code: ' + code);
    });
    console.log(`File ${file.name} metadata updated.`);
  }

  callback();
};

**Comment by kpr6** [comment]
Here, I'm trying to run a jar file using node js spawn. Can't see any syntax error yet :\

**Comment by jmdobry** [comment]
So you're getting that error when you run the `functions deploy` command? Can you post the full command that you're using?

**Comment by kpr6** [comment]
Yes.
`functions deploy dataflow1 --trigger-bucket=cloudfunctions-test`

**Comment by jmdobry** [comment]
And you're running that command in the directory that contains your index.js, package.json, and jar files? And the result of the deploy command is `RequestError: socket hang up`?

**Comment by kpr6** [comment]
yes, true!
Also it has the jre folder too

**Comment by jmdobry** [comment]
Hmm, can you try the deploy again, then after it fails, post here the output of:

1. `functions logs read`
1. `functions config list -j`
1. `functions status`

**Comment by kpr6** [comment]
<img width="1280" alt="screen shot 2017-06-17 at 07 55 33" src="https://user-images.githubusercontent.com/10363215/27249406-738b57ea-5332-11e7-9989-dd9cd6a77857.png">

**Comment by sjurgis** [comment]
Same here - error on deploy and call.

**Comment by kpr6** [comment]
@sjurgis Can you check code for any errors coz when i try to deploy it to cloud functions. It gives out this error 
```
D      dataflow  129834524734723  2017-06-14 09:32:44.764  Function execution started
I      dataflow  129834524734723  2017-06-14 09:32:45.365  File abc.txt metadata updated.
E      dataflow  129834524734723  2017-06-14 09:32:45.560  error: jre/bin/java: 1: jre/bin/java:
D      dataflow  129834524734723  2017-06-14 09:32:45.560  Function execution took 797 ms, finished with status: 'ok'
D      dataflow  129834524734723  2017-06-14 09:32:45.564  Ignoring exception from a finished function
E      dataflow  129834524734723  2017-06-14 09:32:45.567  error: Syntax error: "(" unexpected
D      dataflow  129834524734723  2017-06-14 09:32:45.567  Ignoring exception from a finished
function
E      dataflow  129834524734723  2017-06-14 09:32:45.569  error:
D      dataflow  129834524734723  2017-06-14 09:32:45.569  Ignoring exception from a finished function
I      dataflow  129834524734723  2017-06-14 09:32:45.655  closing code: 2
```
I have "jre" folder in my working directory too.

**Comment by jmdobry** [comment]
@kpr6 I feel like something is messed up with your emulator installation. Can you:

1. Stop the emulator
1. Ensure you don't have any renegade emulator Node.js processes running
1. Uninstall the emulator
1. Delete this directory: `~/.config/configstore/@google-cloud/functions-emulator/`
1. Ensure you don't have any other programs using the emulator's default ports
1. Re-install and start the emulator

    Note: You shouldn't have to use `sudo` to install the emulator, if you do, that could cause problems with the emulator's execution.

**Comment by jmdobry** [comment]
Please check out the [Troubleshooting Guide](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Troubleshooting)

If it doesn't help, please comment back on this issue with more details steps to reproduce your error.
