### ISSUE TITLE
Error deployign functions

### ISSUE THREAD

**Issue by marceloguaycurus** [GoogleCloudPlatform/cloud-functions-emulator#123]
Hi!

I've been following this tutorial to initiate at Google Cloud: https://cloud.google.com/functions/docs/tutorials/ocr

Everything was working great until I started getting an error on deploying functions:

1. $ gcloud beta functions deploy ocr-extract --stage-bucket reader_project_files --trigger-bucket 
reader_project_images --entry-point processImage
2. Copying file:///var/folders/cg/5yn97vyd64l76x19jtzzcpfh0000gn/T/tmpz45uOt/fun.zip [Content-Type=application/zip]...
3. - [1 files][  3.3 KiB/  3.3 KiB]                                                
4. Operation completed over 1 objects/3.3 KiB.                                      
5. Deploying function (may take a while - up to 2 minutes)...failed.              
**ERROR: (gcloud.beta.functions.deploy) OperationError: code=13, message=The service has encountered an internal error. Please try again later**

I've tried waiting for 3 hours and the error persisted. After that I deleted the hole project, created a new one and tried again. Same error. 

Can anyone help me with that?

Thanks!

**Comment by jmdobry** [comment]
Hi @marceloguaycurus, can you move your question over to the public issue tracker for Cloud Functions? https://issuetracker.google.com/issues?q=status:open%20componentid:187195

**Comment by marceloguaycurus** [comment]
Hi, @jmdobry , the next day it started working correct without doing anything. In this case I think it's better if I just close the issue, right?
If it still better to post the error there, just let me know. Thanks!

**Comment by jmdobry** [comment]
Yes, the error you posted belongs on the Cloud Functions public issue tracker.
