### ISSUE TITLE
Cannot deploy more than 100 functions from single module (file)

### ISSUE THREAD

**Issue by huysamen** [GoogleCloudPlatform/cloud-functions-emulator#125]
### Description

It is currently impossible to deploy more than 100 functions from a single module.  For example, we are using the Serverless framework with Webpack and Typescript, so everything gets bundled into a single `index.js` file from which deployment happens (no problem on actual GCF).

I have identified the issue happens because of the following line:
`cloud-functions-emulator/blob/master/src/cli/controller.js:130`

with the culprit:
`node -e "console.log(Object.keys(require('${pathForCmd}') || {})); setTimeout(function() { process.exit(0); }, 100);"`

Unfortunately, the default behaviour of `console.log()` is to, after 100 items of an array, print out:
`... x more items ]`

The logic in the deploy code just tries to match the words in the array, so you can try to deploy a function with the name `more` or `items` and it will always pass the first check and only fail when it actually cannot find an exported function with the name `more` or `items`.

Just stabbing here but using something like `JSON.stringify()` can solve this issue.

### Steps to reproduce

Export more than 100 functions from a single file (as our case with Webpack) and try to deploy the 101st function.

Thanks!

**Comment by jmdobry** [comment]
Should be an easy enough fix.
