### ISSUE TITLE
Module version mismatch. Expected 48, got 51.

### ISSUE THREAD

**Issue by sshniro** [GoogleCloudPlatform/cloud-functions-emulator#128]
I previously installed the cloud function emulator with node version 7 and got this error when I try to deploy a hello world function.
Warning: You're using Node.js v7.10.0 but Google Cloud Functions only supports v6.11.1.

So I installed n and switched to 6.11.1 and removed all the node modules and ran a npm install again. But this time Im getting this error.

Error: Module version mismatch. Expected 48, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/grpc/src/node/src/grpc_extension.js:45:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
Could not figure out how to fix this issue. Any guidance would be appreciated.

Thanks!

**Comment by zbaig** [comment]
I got the same issue. Try these steps:
nvm ls -> v6.11.1
rm -rf node_modules
npm install -g firebase-tools
npm install --save firebase-functions
npm install
firebase serve --only functions --project XXX

Do not see the error you are seeing anymore

However I see this now, still debugging if I can actually make this work (first cloud function btw):
i  functions: Preparing to emulate HTTPS functions. Support for other event types coming soon.
i  functions: No HTTPS functions emulated. Support for other function types are coming soon.

**Comment by nirojans** [comment]
Thanks zbaig. I have removed the folder completely and reinstalled then it worked fine. Not sure why just simply switching to node 6 and remove node modules (+reinstall) did not work.

**Comment by jmdobry** [comment]
The reason is didn't work when you switched Node versions is explained in [#129](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/126#issuecomment-319708141).

**Comment by Archi20** [comment]
Hi!
similar issue but @zbaig solution didn't work for me :( 

`!  functions: Cannot start emulator. Error: Module version mismatch. Expected 48, got 57.`

before 'firebase serve --only functions'  I did every step form @zbaig answer twice, but it didn't helped, i used `npm cache clean` before deleting node_modules with the same results.

node versions:
`
    8.2.1
  * 6.11.1 (Currently using 64-bit executable)
`
Any ideas to resolve the problem? 
Thanks!

**Comment by jmdobry** [comment]
This error happens when you attempt to run module that has native extensions with a version of Node that is different than the version of Node that was used to install it.

What does this mean?:

node versions:
`
    8.2.1
  * 6.11.1 (Currently using 64-bit executable)
`

Are you using 8.2.1 or 6.11.1?

**Comment by Archi20** [comment]
Hi @jmdobry !
I am using 6.11.1 version now and I made every step from  @zbaigs list. Before I had used 8.2.1 version of node.js.

**Comment by jmdobry** [comment]
Then somehow, the `grpc` npm package that's still on your machine was installed with 8.2.1. You could try:

```
nvm ls -> v6.11.1 (make sure)
rm -rf node_modules
npm uninstall -g firebase-tools
npm uninstall -g @google-cloud/functions-emulator
npm install -g firebase-tools
npm install --save firebase-functions
npm install
firebase serve --only functions --project XXX
```

**Comment by Archi20** [comment]
Hi!
Thank You for your reply. Unfortunetly didn't work, that was problem with patch v6.11.1 have been installing in diffrent directory than firebase serve want started. I don't know why. I uninstalled everytnig with node.js, firebase-tools and nvm also, and download lastest sable version v6.11.3. I have installed globally firebase-tools, and.. I have another issue :( 
`firebase serve --only functions`
result:
`Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.`

**Comment by Archi20** [comment]
Ok, I have solved my problem! It was stupid, just inside functions directory start npm install, not just in whole project. 
Truly thank you for yours suggestions!

**Comment by whydna** [comment]
I'm getting the same error here after switching my node version using NVM to 6.11.X form 9.x .

Have tried everything including uninstalling all packages, removing node_modules folder, `npm cache clear`, even deleting the entire functions module and re-initializing it. 

`⚠  functions: Cannot start emulator. Error: Module version mismatch. Expected 48, got 57.`

**Comment by Archi20** [comment]
Hi @whydna 
Try go into firebase functions folder and run firebase serve --only functions.

**Comment by Shery11** [comment]
i tired everything still no luck
