### ISSUE TITLE
Nuxt middleware

### ISSUE THREAD

**Issue by numfin** [GoogleCloudPlatform/cloud-functions-emulator#129]
### Description

(caution! not native english)
Hi, i have one problem with nuxt render.
Here is my "working code" but still give me timeout errors.
Can you help me to fix it? Im nooby

```
const express = require("express")();
const config = require("./nuxt.config.js");
const { Nuxt, Builder } = require("nuxt");
const nuxt = new Nuxt(config);
const builder = new Builder(nuxt);
const build = builder.build();

express.use(nuxt.render);

exports.app = functions.https.onRequest(express); 
```

### `firebase serve --only functions`
> error:  code=500, status=INTERNAL, message=Function worker killed by signal: SIGTERM, errors=[Function worker killed by signal: SIGTERM]
> ! functions: Error from emulator. undefined

### ` firebase deploy --only functions`
> deploying functions
> functions: ensuring necessary APIs are enabled...
> runtimeconfig: ensuring necessary APIs are enabled...
> runtimeconfig: all necessary APIs are enabled
> functions: all necessary APIs are enabled
> functions: preparing functions directory for uploading...
> functions: packaged functions (100.26 KB) for uploading
> functions: functions folder uploaded successfully
> starting release process (may take several minutes)...
> functions: updating function app...
> functions[app]: Deploy Error: Function load error: Error: function load attempt timed out.

Thanks!

p.s. If you need more information (because of my lang skills) just tell me. I'll show everything, but i really really need your help

**Comment by fortil** [comment]
@numfin Do you have anythinks?

**Comment by numfin** [comment]
@fortil i did nothing :C
