### ISSUE TITLE
HTTP request size limit does not match Google Cloud Functions limit

### ISSUE THREAD

**Issue by divyenduz** [GoogleCloudPlatform/cloud-functions-emulator#136]
### Description

According to the [docs](https://cloud.google.com/functions/quotas) the maximum request size is 10MB. Emulator, however, is limited by `body-parser` [default limit of 100KB](https://github.com/expressjs/body-parser#limit)

I think this can be resolved by adding limit to config of `body-parser` around these [lines in emulator code](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/blob/master/src/supervisor/supervisor.js#L70).

Please let me know if this is correct. I can come up with a PR. 

### Steps to reproduce

1. Create a function and try to send request body greater than 100KB. I was trying to send base64 audio file and ran into the error
<img width="426" alt="screen shot 2017-08-25 at 1 17 42 pm" src="https://user-images.githubusercontent.com/746482/29704525-d2330c84-8997-11e7-91c6-fc682e1bbea0.png">

Please advise.  

Thanks!

**Comment by jmdobry** [comment]
Fixed by #152 in `1.0.0-alpha.26`
