### ISSUE TITLE
Emulator failed to start

### ISSUE THREAD

**Issue by jsbranco** [GoogleCloudPlatform/cloud-functions-emulator#139]
### Description
I am using ubuntu 16.04, I installed functions following the documentation in https://cloud.google.com/functions/docs/emulator.

However, when I attempt to start the emulator it throws an error:

> Warning: You're using Node.js v8.1.0 but Google Cloud Functions only supports v6.11.1.
> Google Cloud Functions Emulator RUNNING
> ERROR: TypeError: Cannot read property 'functions' of undefined
>     at _action.then (/home/junio/.nvm/versions/node/v8.1.0/lib/node_modules/@google-cloud/functions-emulator/src/client/rest-client.js:142:39)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:169:7)

I also tried using nvm install 6.11.1 and use that version to follow the steps in the documentation, however when I run it, still throws the same error.
`functions --version
1.0.0-alpha.25
`
Has anyone encountered this issue before?

**Comment by jmdobry** [comment]
`node -v` needs to produce `v6.11.1` in order for that warning to go away. Also, both the emulator and firebase tools themselves need to have been installed using Node v6.11.1.

**Comment by jmdobry** [comment]
Please check out the [Troubleshooting Guide](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Troubleshooting)

If it doesn't help, please comment back on this issue with more details steps to reproduce your error.
