### ISSUE TITLE
Functions emulator does not automatically parse the body

### ISSUE THREAD

**Issue by sarunint** [GoogleCloudPlatform/cloud-functions-emulator#141]
### Description

Note: I use `firebase-tools` to run the emulator.

According to [this](https://cloud.google.com/functions/docs/writing/http) and [this](https://firebase.google.com/docs/functions/http-events), the function should automatically parse the body. But it seems that the body is not parsed while using the emulator. (On the cloud it works fine)

### Steps to reproduce

This is the code:

```typescript
import * as firebase from 'firebase-admin';
import * as functions from 'firebase-functions';
import * as _cors from 'cors';

const cors = _cors({ origin: true });

firebase.initializeApp(functions.config().firebase);

export const myfunction = functions.https.onRequest((req, resp) => {
  cors(req, resp, () => {
    if (req.method.toLowerCase() !== 'post') {
      resp.status(405).end();
    } else {
      const data = req.body;
      const username = data.username;
      const password = data.password;
      console.log(typeof data);
      console.log(username);
      console.log(password);
      resp.status(200).end();
    }
  });
});
```

Then I send a request to the function using [Postman](https://www.getpostman.com) like this:

![image](https://user-images.githubusercontent.com/3850197/30519414-08c71616-9bc0-11e7-9540-0fe13e7fc4ae.png)

and this is what appeared in the console:

```
info: User function triggered, starting execution
info: string
info: undefined
info: undefined
info: Execution took 15 ms, user function completed successfully
```

Shouldn't `typeof data` be `object`? I'm not quite sure.

Thanks!

**Comment by jmdobry** [comment]
Hmm, I have been unable to reproduce. I deployed your function and made the same request with Postman, and I get 

```
info: User function triggered, starting execution
info: object
info: username
info: password
info: Execution took 13 ms, user function completed successfully
```

**Comment by sarunint** [comment]
Hmm, I tried again and now I'm unable to reproduce the issue this time.

I'm going to close this for now. And will reopen when I have more encounters with the issue.
