### ISSUE TITLE
how to specify port

### ISSUE THREAD

**Issue by cyrfer** [GoogleCloudPlatform/cloud-functions-emulator#153]
Where are instructions on how to specify the port when running cloud functions locally?

It seems like it should be here:
https://firebase.google.com/docs/functions/local-emulator

**Comment by jmdobry** [comment]
I'm not actually sure when the emulator is being using from Firebase tools. You might try editing `~/.config/configstore/@google-cloud/functions-emulator/config.json`

/cc @laurenzlong

**Comment by laurenzlong** [comment]
If you are using the Firebase CLI, you can specify the port like so:

```
firebase serve --only functions --port=9000
# or 
firebase experimental:functions:shell --port=9000
```
