### ISSUE TITLE
Outdated grpc dependency is broken on windows 10, Kindly update

### ISSUE THREAD

**Issue by somombo** [GoogleCloudPlatform/cloud-functions-emulator#158]
### Description

It appears that the `grpc@1.6.6` dependency will not install on windows 10 
(note: I am aware that this requires native addons setup and have correctly installed [npm windows build tool](https://github.com/felixrieseberg/windows-build-tools))

After I bumped this dependency up to ^1.6.6, everything worked fine.

### Steps to reproduce

Try `npm install grpc@1.6.6`  on a windows 10 machine, it should fail. However `npm install grpc@^1.6.6` should work fine.

Thanks!

**Comment by somombo** [comment]
Nevermind.. I downgraded from Node.js v9.0.0 to v8.9.0 and now it appears to work.
Feel free to close out this issue, or you can update that dependency if it's still worthwhile.. 

I'll leave this issue open here in case anyone else has this problem.

**Comment by jmdobry** [comment]
`grpc` has been updated to `1.7.1` in `1.0.0-alpha.26`

**Comment by somombo** [comment]
Appreciate it
