### ISSUE TITLE
Debugging doesn't work with current node version

### ISSUE THREAD

**Issue by natevw** [GoogleCloudPlatform/cloud-functions-emulator#186]
#### Environment details

  - OS: macOS 10.13.2
  - Node.js version: 9.3.0
  - npm version: 5.6.0
  - @google-cloud/functions-emulator version: 1.0.0-alpha.29

#### Steps to reproduce

  1. Following the instructions at <https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Debugging-with-Visual-Studio-Code>…
  2. …when I run `functions debug helloWorld` it doesn't work

Instead of it starting a debugger, I get:

> Warning: You're using Node.js v9.3.0 but Google Cloud Functions only supports v6.11.5.
> ERROR: Function worker crashed with exit code: 9
> undefined(node:16736) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.

**Comment by phatakrajan** [comment]
Any resolution to above issue? I am also facing same issue

**Comment by irons** [comment]
Install [nvm](https://github.com/creationix/nvm), use nvm to install a node 6.11.5 environment, and invoke functions-emulator using that environment.

**Comment by natevw** [comment]
I think @irons is on to the real solution here (at least as far as this emulator is concerned).

A careful re-reading of the message says:

> … but **Google Cloud Functions** only supports v6.11.5

i.e. it's not that the *emulator* doesn't/couldn't support newer engines. It's the actual real service that's really stuck on an older node right now. While it still might be handy to still debug with whatever node is generally on the system, it puts you in dangerous territory.

E.g. I used `Object.entries` which worked in my emulator with a newer node, but crashed when deployed. If I'd heeded the warning, used a solution like nvm or whatever to deal with it, I would have been able to debug from VS Code **and** caught real-world issues like this earlier.

**Comment by sluongng** [comment]
I used nvm and installed node to v6.11.5 but still got this issue
```
~/work/misc/gif-bot> node --version
v6.11.5
~/work/misc/gif-bot> functions-emulator debug first
ERROR: Function worker crashed with exit code: 9
undefined(node:10726) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
~/work/misc/gif-bot>
```

the function supposed to be basic hello world function so...

**Comment by robertlevy** [comment]
Seeing the same thing here as @sluongng's last comment

**Comment by natevw** [comment]
@sluongng @robertlevy Sounds like you might want to open a new ticket "debugging doesn't work *even with **supported** node.js version*" since in this case here it wasn't entirely unexpected for the debugging to fail.

**Comment by briodev-zz** [comment]
instead of debug I used inspect and worked on my mac

functions inspect helloworld
Warning: You're using Node.js v9.8.0 but Google Cloud Functions only supports v6.11.5.
Debugger for helloworld listening on port 9229.
