### ISSUE TITLE
Environment variables not working

### ISSUE THREAD

**Issue by sashokbg** [GoogleCloudPlatform/cloud-functions-emulator#197]
Hello,

I am having a problem reading an environment variable within a deployed function via process.env.VARNAME

I have tried setting the variable while running the process like so:

MDE_DEBUG=true && functions deploy savetoken -H

Then I have tried setting it in the .bashrc but still no luck - it shows as undefined in my code.
 
#### Environment details

  - OS: Ubuntu
  - Node.js version: 6.11.5 (as recommended by google)
  - npm version: 3.10.10
  - @google-cloud/functions-emulator version: 1.0.0-beta.3

#### Steps to reproduce

  1. Create a function
  2. Reference an env variable within with process.env.VARNAME

#### Other infos

I have manually edited the "functions" executable and added the following line:

vim /home/alexander/.nvm/versions/node/v6.11.5/bin/functions

```console.log(`Running emulator. Env : ${JSON.stringify(process.env)}`);```

Then when I run **functions deploy** .. I can see my env variable present int the **process.env** object which means that variable is present and visible to the launched node process.

Thank you for your help.

Best Regards
Alexander KIRILOV

**Comment by sashokbg** [comment]
As strange as it is - today everything works fine ! It must have been a problem with my environment

**Comment by dukuo** [comment]
I'm using Windows 10 64bit and I set NODE_ENV vars in my machine but it's undefined in the emulator. How do you exactly define environment variables using the emulator?
