### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by kaspermarstal** [GoogleCloudPlatform/cloud-functions-emulator#20]
### Description

Promises are not handled as expected by the cloud-functions emulator. For example, all functions from the [nodejs-docs-samples/functions/datastore](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/functions/datastore) test suite that rely on promises return the following error:

```
{
  "stack": "TypeError: Cannot read property 'then' of undefined\n    at Object.set (/Users/kasper/Development/google-app-engine/server/modules/datastore/functions.js:69:5)\n    at Object.invoke (/usr/local/lib/node_modules/@google-cloud/functions-emulator/src/emulator/invoker.js:38:15)\n    at Object._invoke (/usr/local/lib/node_modules/@google-cloud/functions-emulator/src/emulator/index.js:439:19)\n    at /usr/local/lib/node_modules/@google-cloud/functions-emulator/src/emulator/index.js:383:14\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/route.js:131:13)\n    at next (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/route.js:125:14)\n    at next (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/route.js:125:14)\n    at next (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/route.js:125:14)\n    at next (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/route.js:125:14)",
  "message": "Cannot read property 'then' of undefined"
}
```
### Steps to reproduce

- Deploy [nodejs-docs-samples/functions/datastore](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/functions/datastore) to cloud-functions-emulator
- Execute the following request against `http://localhost:8008/set` (I used [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop))

```
{
  method: `POST`,
  headers: {
    'Content-Type': `application/json`
  },
  body: {
    kind: datastore.kind.BOOK,
    key: `ilovebike`,
    value: { title: `I love bike` }
  }
}
```

Looking forward to using this wonderful tool!

**Comment by jmdobry** [comment]
Are you using the `0.4.0` version of the emulator currently published to NPM?

**Comment by kaspermarstal** [comment]
Yes I am using `0.4.0`. However, I was perhaps a little too trigger happy when opening this issue and after a bit of digging it seems the problem is with the porting of GoogleCloudPlatform/nodejs-docs-samples repo. I have opened a new issue at GoogleCloudPlatform/nodejs-docs-samples#284.

Thank you for your time.

**Comment by kaspermarstal** [comment]
The problem persists and is not related to the issue referenced above.

**Comment by jmdobry** [comment]
Resolved via GoogleCloudPlatform/nodejs-docs-samples#284
