### ISSUE TITLE
Node 8 Runtime support

### ISSUE THREAD

**Issue by r00tat** [GoogleCloudPlatform/cloud-functions-emulator#258]
As there is now the new Node 8 runtime out, will this be supported in a future release? 

I know, that it isn't currently supported by functions emulator, but this would be a great help for developing on node 8.

**Comment by r00tat** [comment]
In the meantime I am using express to simulate the basic environment for background functions. In case this is helpful for anyone else trying to switch to node 8, here is my test server:

```javascript
const express = require("express");
const bodyParser = require("body-parser");

const app = express();

const triggers = require('./index');

app.use(bodyParser.json());

for (let name in triggers) {
  // create a trigger for every export
  console.info(`reqistered function ${name}`)

  app.post(`/${name}`, (req, res) => {
    let {
      data,
      context
    } = req.body;
    if (data === undefined || context === undefined) {
      res.status(400).json({
        error: "data and context is required as json body"
      });
      return;
    }

    triggers[name](data, context, error => {
      if (error) {
        res.status(500).json(error)
      } else {
        res.status(200).json({
          status: "OK"
        })
      }
    })
  });
}


// Start the server
const PORT = process.env.PORT || 8080;
app.listen(PORT, () => {
  console.log(`App listening on port ${PORT}`);
  console.log('Press Ctrl+C to quit.');
});
```

You're now able to test your function by using curl and sending the event as json:

```bash
curl -vX POST http://localhost:8080/bqImport -d @examples/event.json --header "Content-Type: application/json"
```

**Comment by rogiervandenberg** [comment]
@r00tat Yes, I am having the same issue, trying to build a Cloud Function that is triggered by PubSub, following [this explanation](https://cloud.google.com/functions/docs/writing/background#functions_background_parameters-node8) and it works online. But locally stuff crashes..

Can you explain how I can use your server to locally develop my PubSub triggered background-function?

**Comment by torbjornvatn** [comment]
I would also love to be able to test function locally that uses the async/await pattern.

**Comment by r00tat** [comment]
@rogiervandenberg you save the example provided above as test.js and by using curl you can call the google cloud function by name. The name of the function will be used as url. 

My example code only works, if you're using the callback inside the cloud function. For promises this can also be adopted. 

This is a good guess, but was not tested:

```javascript
const express = require("express");
const bodyParser = require("body-parser");

const app = express();

const triggers = require('./index');

app.use(bodyParser.json());

for (let name in triggers) {
  // create a trigger for every export
  console.info(`reqistered function ${name}`)

  app.post(`/${name}`, (req, res) => {
    let {
      data,
      context
    } = req.body;
    if (data === undefined || context === undefined) {
      res.status(400).json({
        error: "data and context is required as json body"
      });
      return;
    }

    let triggerPromise = triggers[name](data, context, error => {
      if (error) {
        res.status(500).json(error)
      } else {
        res.status(200).json({
          status: "OK"
        })
      }
    })

    if (triggerPromise && triggerPromise instanceof Promise){
      triggerPromise.then(result => {
        res.status(200).json(result);
      }).catch(err => {
        console.error("trigger failed", err),
        res.status(500).json(error);
      })
    }
  });
  
}


// Start the server
const PORT = process.env.PORT || 8080;
app.listen(PORT, () => {
  console.log(`App listening on port ${PORT}`);
  console.log('Press Ctrl+C to quit.');
});
```

**Comment by rogiervandenberg** [comment]
@r00tat Thanks, you've inspired me to make something to easily dev with HTTP and then convert it into a pub/sub function. 👍

**Comment by aronsuarez** [comment]
any update on this?

**Comment by chen86860** [comment]
Please supported as soon as.  I can't wait for~

**Comment by fgilio** [comment]
I don't know why @r00tat code didn't work for me, here's what I ended up doing:
```js
const express = require('express');
const bodyParser = require('body-parser');

const app = express();

const triggers = require('./index');

app.use(bodyParser.json());

for (let name in triggers) {
    // create a trigger for every export
    console.info(`Reqistered function ${name}`)

    app.post(`/${name}`, (request, response) => {
        triggers[name](request.body, response)
    });
}


// Start the server
const PORT = process.env.PORT || 8080;
app.listen(PORT, () => {
    console.log(`App listening on port ${PORT}`);
    console.log('Press Ctrl+C to quit.');
});
```

**Comment by r00tat** [comment]
More than a half year and still only on nodeJS 6 support... node 8 is there for some time and even app engine even moved to version 10.
For a developer experience that's really not the best you can get.

**Comment by fgilio** [comment]
The whole Cloud Functions thing seems to be left behind, this kind of stuff makes me want to be using Lambda

**Comment by mecurc** [comment]
Recently I discovered Cloudflare workers. Guys, try it ;-) 

- 50% costs

**Comment by dinvlad** [comment]
We'd also like to use Functions Emulator for automated security testing (e.g. with ZAP).

**Comment by r00tat** [comment]
[@google-cloud/functions-framework](https://github.com/GoogleCloudPlatform/functions-framework-nodejs) was released yesterday. This covers the functionality we have been asking for.

**Comment by fgilio** [comment]
Thanks for the heads up @r00tat

**Comment by grant** [comment]
Hey all,
As @r00tat mentioned, we've released the [functions framework for Node 10](https://github.com/GoogleCloudPlatform/functions-framework-nodejs). This is the underlying framework used for both deployed cloud functions in GCF Node 10 and can be used for local development.

The team and I will be working on enhancing the developer experience there for Node. We'd love your issues and questions on local development in that repo.

Thanks for your patience!

**Comment by watsab** [comment]
Hi!
I've received an email from the GCP Team saying that with node 6 about to being deprecated we now must use the node 8 runtime. Yet the emulator is not compatible with node 8 (or even 10). @grant should I use the framework instead then? Is this framework compatible with node 8? As node 10 is still in beta I cannot use it for production...
Thanks!

**Comment by kossnocorp** [comment]
I'm also puzzled because I use Firebase Functions and they don't support 10 even in beta. I'm very disappointed to get such a level of support from Google.

**Comment by astanet** [comment]
[Action Required] Update Node.js 6 functions emulator to Node.js 8 as soon as possible

**Comment by shovelend** [comment]
> I'm also puzzled because I use Firebase Functions and they don't support 10 even in beta. I'm very disappointed to get such a level of support from Google.

Same issue here when trying to serve Firebase Functions locally. This is starting to get ridiculous, just stumbled across another problem with the latest `firebase` package where `grpc` can't build it on Node v12...

**Comment by r00tat** [comment]
Node 10 (possibly also 8) is out now: https://github.com/firebase/firebase-tools/releases/tag/v6.8.0
