### ISSUE TITLE
Binary name `functions` conflicts with ZSH built-in

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/cloud-functions-emulator#29]
The `functions` command is a built-in in the ZSH shell. It prints out all the shell function definitions.

**Comment by jmdobry** [comment]
Yep, it also conflicts with the `functions` command of Fish Shell. The new upcoming version of @google-cloud/functions-emulator (on master, not published to NPM yet), adds a `functions-emulator` backup binary to your PATH to avoid this conflict.

**Comment by jmdobry** [comment]
1.0.0-alpha.1 has been released to NPM, install it with:

    npm install -g @google-cloud/functions-emulator@1.0.0-alpha.1

or

    yarn global add @google-cloud/functions-emulator@1.0.0-alpha.1

and then the `functions-emulator` binary should be added to your path

**Comment by kirillzubovsky** [comment]
What do you suggest as a workaround for the `functions` conflict?

**Comment by jmdobry** [comment]
Use `functions-emulator` instead.

**Comment by willbowditch** [comment]
Should the main readme be changed to reflect this? Prevent all the zsh users having to come to this issue first. 
 
Start the Emulator:
 `functions-emulator start`

**Comment by JuubiSnake** [comment]
Late to the party, but for what it's worth, doing the following in your ~/.zshrc will disable the `functions` builtin command:

```
# Disable builtin functions
disable r functions
```

Hope this helps someone out there!

**Comment by mengqiy** [comment]
This deserves better documentation in wherever we want to put FAQs (maybe at the bottom of README).
