### ISSUE TITLE
HTTP function error: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by bretmcg** [GoogleCloudPlatform/cloud-functions-emulator#30]
### Description

On the helloWorld example, doing a curl on the local HTTP endpoint results in the error:
TypeError: Cannot read property 'statusCode' of undefined
    at Promise.resolve.then.then.then (/Users/user/.nvm/versions/node/v6.9.1/lib/node_modules/@google-cloud/functions-emulator/src/supervisor/index.js:136:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)$ 

### Steps to reproduce

- Using 1.0.0-alpha.1
- The quickstart helloWorld (echo 'exports.helloWorld = (req, res) => res.send("Hello, World!");' > index.js)
- $ functions deploy
- $ curl <endpoint>

Thanks!

**Comment by bretmcg** [comment]
I think there was an artifact from a previous emulator version (despite having deleted ~/.config/ dir). Uninstalling via npm and then manually deleting the bin and node_modules dir from npm seems to have done the trick.

**Comment by jmdobry** [comment]
Good, I guess. Hopefully future upgrades can go smoother.
