### ISSUE TITLE
Clean up when delete function or use clear command

### ISSUE THREAD

**Issue by ert78gb** [GoogleCloudPlatform/cloud-functions-emulator#31]
### Description
The emulator not delete the temporary files, when delete a function
<description>

### Steps to reproduce
1. functions deploy [function-name] --trigger-http --entry-point index
2. remember the archive path from the deploy output file:///var/folders/xxxxxxxx-xxxx-x-x-x-x-x or check the --stage-directory settings
3. functions delete [function-name]
4. check stage directory (2nd point)
<steps_to_reproduce>

Would be fine if you delete all unnecessary files, because it should be manually clean the storage.
Maybe it could be an additional parameter e.g. functions delete [function-name] --clean
 
Thanks!

**Comment by jmdobry** [comment]
I'll add a `--clean` option to the `delete` command like you suggest.

**Comment by jmdobry** [comment]
I ended just made the Emulator automatically delete temporary files when a function is deleted.

Will be part of the 1.0.0-alpha.7 release.
