### ISSUE TITLE
Problem using functions-emulator after upgrade

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/cloud-functions-emulator#33]
Did the config format change? I get an error for every command now that I just upgraded.

```
$ functions-emulator configs list
Inferring project ID from Cloud SDK config. Speed up CLI commands by setting a project ID: functions config set projectId YOUR_PROJECT_ID or export GCLOUD_PROJECT=YOUR_PROJECT_ID
ERROR: Invalid value 'listEventsPage': Function name must contain only Latin letters, digits and a hyphen (-). It must start with letter, must not end with a hyphen, and must be at most 63 characters long.
```

Where is the config file stored so I can delete it?

**Comment by tswast** [comment]
Found it at ` ~/.config/configstore/@google-cloud/functions-emulator/config.json`.

Except after removing it I still get an error. Maybe the deployed functions are stored somewhere else?

**Comment by tswast** [comment]
I see there are hidden files in that same directory.

```
$ ls -al ~/.config/configstore/@google-cloud/functions-emulator/
total 96
drwx------  7 swast  eng    238 Feb  9 17:04 .
drwx------  3 swast  eng    102 Jan 30 13:56 ..
-rw-------  1 swast  eng    686 Feb  9 17:04 .active-server.json
-rw-------  1 swast  eng  30272 Feb  9 16:48 .discovery.json
-rw-------  1 swast  eng    366 Feb  9 16:48 .functions.json
-rw-------  1 swast  eng      2 Feb  9 16:48 .operations.json
-rw-------  1 swast  eng    461 Feb  9 17:04 config.json
```

After removing the directory, I'm able to start the emulator again.

Feel free to close, unless you want to look into the incompatibility between versions (or document how to reset the server configs).

**Comment by jmdobry** [comment]
The [release notes for 1.0.0-alpha.1](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/releases/tag/1.0.0-alpha.1) had the instructions for deleting that config directory if you have difficulty upgrading. Until this tool reaches 1.0.0 stable I recommend the following when upgrading:

1.  Stop any currently running emulator (this is important!):

       functions stop

    or

        functions-emulator stop

1.  Uninstall the current version:

        npm uninstall -g @google-cloud/functions-emulator

1.  Delete the existing config (see the [release notes](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/releases/tag/1.0.0-alpha.1)).
1.  Install the new version:

        npm install -g @google-cloud/functions-emulator
