### ISSUE TITLE
Cannot pass query string to cloud functions

### ISSUE THREAD

**Issue by scomma** [GoogleCloudPlatform/cloud-functions-emulator#45]
### Description

Currently cloud functions are not able to access the request's query string. `req.query` always finds a blank object.

### Steps to reproduce

1. Access `http://localhost:8010/<projectId>/us-central1/dispatch?abracadabra=1`
2. `req.query['abracadabra'] => undefined`

Happy to contribute if anyone can point me in the right direction.

**Comment by scomma** [comment]
Thank you for a very prompt response!

**Comment by jmdobry** [comment]
Thanks for reporting it!
