### ISSUE TITLE
Deploying an already deployed function should update the existing function, not fail

### ISSUE THREAD

**Issue by MartinSahlen** [GoogleCloudPlatform/cloud-functions-emulator#48]
### Description

If a function exists (i.e. is already deployed) in the emulator, it gives you an error. The production environment updates the function.

### Steps to reproduce

1. deploy a function to the emulator, then deploy it again => `ERROR: Function helloWorld in <region><project> already exists`

2. deploy a function to the prod environment, then deploy it again => `[...]Deploying function (may take a while - up to 2 minutes)...done.`

Thanks!

**Comment by jmdobry** [comment]
I was aware of this, but had lost track of the todo item.
