### ISSUE TITLE
Display on default console window in Mac is difficult to read

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/cloud-functions-emulator#52]
### Description

The default console (Terminal) window on Mac has a white background.  The display of data from the emulator is a little difficult to read.

![screen shot 2017-03-03 at 10 19 59 am](https://cloud.githubusercontent.com/assets/764528/23563346/28cec50a-fffb-11e6-9097-4ad40dcc819d.png)

**Comment by jmdobry** [comment]
Just drop use of colors?

**Comment by jmdobry** [comment]
I came up with some improvements.
