### ISSUE TITLE
HTTP Function hangs when debugging

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/cloud-functions-emulator#53]
### Description

I have a simple HTTP function, literally copied from the default function that you get when you create a new HTTP Function in the UI:

```Javascript
exports.helloWorld = function helloWorld(req, res) {
  // Example input: {"message": "Hello!"}
  if (req.body.message === undefined) {
    // This is an error case, as "message" is required.
    res.status(400).send('No message defined!');
  } else {
    // Everything is okay.
    console.log(req.body.message);
    res.status(200).send('Success: ' + req.body.message);
  }
};
```

When debugging (with default emulator setting) using Visual Studio Code, I "attach" to the emulator (after having started with `--debug`) and my break point fires after issuing a `curl` command from the terminal.  Hitting "play" in VS Code *seems* to cause execution to continue, but the function doesn't return from the `curl` command

**Comment by jmdobry** [comment]
I was able to reproduce this issue with 1.0.0-alpha.6, but it appears to be fixed by #55
