### ISSUE TITLE
New logs not written and/or function not updated

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/cloud-functions-emulator#59]
### Description

I updated the code for a function that was already deployed and added a `console.log()` command, but this doesn't appear in the logs when I issue `functions logs read`.  Not sure if this means the function wasn't updated, or the logs were written somewhere else, or not written at all.

Additionally the log file seems to be undiscoverable (I wanted to view the actual file).  `functions config list` shows `logs/cloud-functions-emulator.log` as the log file setting, but this is not useful as I don't really know where that is.  A search of my computer for `cloud-functions-emulator.log` yields 0 results (although that might be a local index issue (?)

I recommend we show (somewhere) the full path to the log file

**Comment by jmdobry** [comment]
`functions status` shows the full path to the log file

**Comment by jmdobry** [comment]
Regarding the first part, I am unable to reproduce. Is this still an issue?

**Comment by qmacro** [comment]
New here, so may be off the mark. But I noticed a similar issue this weekend, and looked into it. 

The emulator uses [winston](https://www.npmjs.com/package/winston) for logging, and with the [config](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/blob/2c6f8e48afe03dc812c6f3171312368a59ea8183/src/emulator/main.js#L102-L112) specifying a `maxsize` the files will be rotated, with the newer one gaining a numeric suffix. 

So even though the status shows e.g. `[...]/cloud-functions-emulator.log` as the logfile, the live one may be something like `[...]/cloud-functions-emulator1.log`.

**Comment by jmdobry** [comment]
@jasonpolites I guess we should just remove the `maxsize` parameter? Or do we need to revisit the Emulator's logging story in general?

**Comment by kmaillet-arcane** [comment]
Hi all,

I'm having this exact issue. The logs are not updated anymore even though my function works as expected. 
Do you have any updates on a fix?
Thanks !

**Comment by jmdobry** [comment]
The fix should go out with 1.0.0-alpha.21
