### ISSUE TITLE
Make simulation of bucket triggers possible in emulator 

### ISSUE THREAD

**Issue by xrd** [GoogleCloudPlatform/cloud-functions-emulator#6]
### Description

I'd like to be able to support simulation of bucket triggers.

### Example Call

`functions call helloWorld --trigger-bucket --file sample.mov --state not_exists`

This call will provide this kind of data into the function.

```javascript
{ 
  kind: 'storage#object',
  resourceState: 'not_exists',
  id: 'abcdef-150105-bucket/sample3.mov',
  selfLink: 'https://www.googleapis.com/storage/v1/b/abcdef-150105-bucket/o/sample.mov',
  name: 'sample.mov',
  bucket: 'abcdef-150105-bucket',
  generation: '1479794297769000',
  metageneration: '1',
  contentType: 'video/quicktime',
  updated: '2016-11-22T05:58:17.760Z',
  timeDeleted: '2016-11-22T06:04:17.998Z',
  size: '4838590',
  md5Hash: 'ODg1ZGNkZDZlMzNlMTZmMDgzNzQ0OTUyOGUzMDllOTg=',
  mediaLink: 'https://www.googleapis.com/storage/v1/b/abcdef-150105-bucket/o/sample.mov?generation=1479794297769000&alt=media',
  crc32c: 'RS8o1Q==' 
}
```

**Comment by jasonpolites** [comment]
Simulating every possible event type (current and future) in the CLI directly might be difficult.  How about if we supported the [--data-binary](https://curl.haxx.se/docs/manpage.html#--data-binary) option like curl?  This would mean you can easily create the JSON document on the file system and send it to the function.  Would that work?

**Comment by bytravelers** [comment]
That seems more reasonable. I am no longer so concerned about having it in the CLI after more thought. Happy Thanksgiving!

**Comment by xrd** [comment]
That seems more reasonable. I am no longer so concerned about having it in the CLI after more thought. Happy Thanksgiving!

**Comment by jasonpolites** [comment]
Roger that.. closing this in preference for corresponding enhancement issue  (#8)
