### ISSUE TITLE
GCP_PROJECT environment variable not set

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/cloud-functions-emulator#60]
### Description

The production environment sets the GCP_PROJECT env var (same value as GCLOUD_PROJECT).  UUIC there may be some libs which look for this value, but the emulator does not set it.

**Comment by jmdobry** [comment]
I've never seen this variable before, maybe as some point the Cloud client libraries looked for it. Now they're generally look for `GCLOUD_PROJECT` or `GOOGLE_CLOUD_PROJECT`.

**Comment by jmdobry** [comment]
But I'll update the Emulator, if this is was prod does.
