### ISSUE TITLE
Add support for live-reloading of functions.

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/cloud-functions-emulator#62]
Right now, you have to re-deploy a function or restart the Emulator in order for changes to a function to take effect. One solution would be to watch the function's file for changes and re-deploy the function automatically when files change.

**Comment by Alex-Mann** [comment]
Is there an argument to display a log acknowledging when this file has started/finished reloading?

**Comment by jmdobry** [comment]
There isn't any explicit argument, however if you set `verbose` to `true` (`functions config set verbose true` and `functions restart`), then in the logs you'll be able to see the workers shutting down and restarting as you change your code.

When you change your code, the worker will shut down. The next time the function is invoked the worker will start up again, giving you that "cold start" effect.

**Comment by peternann** [comment]
I just wasted a few hours before realising this feature was biting me on the arse... It seems to watch for ANY file changes in the function folder - Is that right?

Well, if you are foolish enough to like your log file created locally, there is a pretty major problem... It keeps clobbering the worker threads milliseconds after any activity goes into the logging!

Could we have some config to control the filespec that is watched??? Ignoring, oh, maybe, *.log perhaps?

**Comment by jmdobry** [comment]
I just added the `--watch` and `--watchIgnore` options in 1.0.0-alpha.24.

You can disable file watching completely with `functions start --watch false`.

You can change what files are ignored with `functions start --watchIgnore node_modules --watchIgnore '.*\.log'
