### ISSUE TITLE
Warning message for versions is a little confusing

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/cloud-functions-emulator#64]
I recently updated the emulator, and when I tried to execute a command I got this message:

`The version of the currently running Emulator  is lower than that of the installed CLI (1.0.0-alpha.11). Please shutdown any running Emulator processes and restart using the installed CLI.`

OK.. that's cool, but it's not super-clear what it's telling me to do. `Please shutdown any running Emulator processes`.. am I supposed to manually kill the process?  Recommend re-phrasing to:

*"The version of the currently running Emulator is lower than that of the installed CLI (1.0.0-alpha.11).  Please manually terminate any running Emulator processes, then restart using the CLI."*

Also there's an extra space between "*Emulator*" and "*is*" in the current message.

Longer term we should look at how we can do this for the user, perhaps with a Y/N warning/question (assuming we can deduce the process ID from the file system etc)

**Comment by jasonpolites** [comment]
Actually... this feels like a bug.  I can't start the emulator at all now.  I've confirmed I have no running processes, but I still just get the warning.

**Comment by jasonpolites** [comment]
Maybe manually killing the process left the PID file on the file system?

**Comment by jmdobry** [comment]
You don't have any node processes at all? Also, try deleting ~/.config/configstore/@google-cloud/functions-emulator.

> Maybe manually killing the process left the PID file on the file system?

Possibly, when you use the CLI to stop the Emulator, the PID is removed. I should update the Emulator to remove its own PID from the filesystem when the process exits.

**Comment by jasonpolites** [comment]
The fix in that commit 4da522b is likely to not work as the user can't invoke the `functions` CLI without the warning, and hence can't call `functions kill`

**Comment by jmdobry** [comment]
I removed the line that prevented the user from calling `functions kill`

**Comment by jmdobry** [comment]
Done
