### ISSUE TITLE
Make worker idle timeout configurable

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/cloud-functions-emulator#66]

**Comment by jpreynat** [comment]
@jmdobry Glad to hear that this is a known issue.
We are currently developing a Firebase hosted web application and we are using `firebase-tools` (backed by `@google-cloud/emulator`) to test it locally.
It would be great to be able to pass the idle timeout configuration from the `firebase serve` command, so at least making it configurable through the emulator's API.
Is this issue planned to be resolved quickly?

**Comment by jmdobry** [comment]
Added `--maxIdle` and `--idlePruneInterval` options to `functions start`
