### ISSUE TITLE
Installation failed with Yarn but works with npm 

### ISSUE THREAD

**Issue by bayareahank** [GoogleCloudPlatform/cloud-functions-emulator#72]
### Description

Actually the install process itself report success when running with yarn, yet running "functions" would fail, with error "Cannot find module 'google-auth-library'". When install with npm, the command works successfully. 

This looks more a yarn bug, but put here anyway so people may know of it. 

### Steps to reproduce

This is generated on Ubuntu 16.04.2 LTS. 
Steps I took to generate this error: 

1. yarn global add @google-cloud/functions-emulator
It failed at the last step to create the symbolic link, since I didn't run with sudo. 

2. sudo yarn global add @google-cloud/functions-emulator
It succeeds at this step, yet the command 'functions' is nowhere to be found. Apparently yarn exits before making the symbolic link. 

3. sudo yarn global remove @google-cloud/functions-emulator
4. sudo yarn global add @google-cloud/functions-emulator
Now we can see functions under /usr/local/bin. 

5. run 'functions' from command line. 
Error: Cannot find module 'google-auth-library'

6. find ~/.config/ -name google-auth-library
/home/user/.config/yarn/global/node_modules/google-auth-library
/home/user/.config/yarn/global/node_modules/googleapis/node_modules/google-auth-library

Thanks!

**Comment by jmdobry** [comment]
Hmm, to reproduce I ran the following (on Mac OS X):

1. `brew update`
1. `brew upgrade node`
1. `brew cleanup node`
1. `brew upgrade yarn`
1. `brew cleanup yarn` (This brought my installed Yarn version up to `0.21.3`
1. `yarn global add @google-cloud/functions-emulator`
1. `functions config set project MY-PROJECT`
1. `functions start`

Everything seems to work fine for me. Can you verify what version of Node.js and Yarn you're using?

Also, to me, using `sudo` at all for anything Node.js-related seems like a yellow flag, and in my experience indicates a borked Node.js installation.

**Comment by bayareahank** [comment]
Thanks for the response, it is worthwhile to point out that you did install on Mac, while the environment that produced the bug is under Linux. 

So my question is, can you point out a way to do global install without sudo? I am very interested to learn the answer.

**Comment by jmdobry** [comment]
What I usually tell people is to wipe any trace of Node.js/NPM from the system and then re-install using [NVM](https://github.com/creationix/nvm).

**Comment by bayareahank** [comment]
For your info., the node.js I run on Linux is 6.9.1, latest version distributed on Ubuntu 16.04.2. Yarn is 0.21.3. 

Having said that, I assume you are talking more from the experience of a Mac and Brew user. Brew modified directory /usr/local/bin's permission on Mac during install, so laptop user can do global install without sudo. For non Brew user or non-Mac user (Linux in my case), you will need sudo to do global install. Whether you should use Brew on Mac or not, is a different topic. 

I also assume you implied node.js version as a main contributor to the bug, which I am not fully convinced. As I mentioned, npm -g works. Whether it comes from the interaction of a specific node.js version (6.9.1) and yarn, it is a possibility. Yet since node.js 6.9.1 is standard install on Ubuntu LTS, I assume a lot of people will run into this problem during installation. 

Reproducing a bug on different OS are totally different things. Maybe I should dig deeper to find out why the library isn't found by 'functions' when using yarn, but since it isn't a show-stopper for me (npm -g works), I leave it more to you guys. Again as I mentioned in the first post, I still suspect it more a bug on the Yarn side. 

Cheers.

**Comment by jmdobry** [comment]
I'm speaking from both Mac and Linux experience (my other workstation is Linux). I use NVM to manage my Node.js installations on Linux, and I never need sudo.

On my Linux workstation I just tried the following (this time using Node v6.9.4 and Yarn installed via their bash script):

1. `yarn global add @google-cloud/functions-emulator`
1. `functions --help`
1. `functions config set projectId MY-PROJECT`
1. `functions start`

Everything worked. Maybe there's just an odd combo of OS/Yarn/Node that's causing the problem.

**Comment by jwrubel** [comment]
FWIW I had this exact scenario with yarn 0.18.1 when I first tried to install. `brew upgrade yarn` to `0.21.3` then `brew cleanup yarn` then reinstall the emulator worked for me.
