### ISSUE TITLE
Warn user when local version of Node is greater than 6.9.1

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleCloudPlatform/cloud-functions-emulator#73]
As Cloud functions only work with Node.js 6.9.1 for now, it would be great if we could add a warning in the console when local version of Node.js is superior to 6.9.1.

Steps to reproduce:
1. I'm playing with async/await in a recent version of Node.js.
2. It runs great locally!
3. I deploy it successfully
4. I run it and it fails ;(

**Comment by jmdobry** [comment]
Good idea. It does currently verify that your version of Node.js is _at least_ 6.9.1, so it will be easy enough to print the warning when you're higher than 6.9.1.
