### ISSUE TITLE
Could not `functions start` on node v4.x

### ISSUE THREAD

**Issue by quangv** [GoogleCloudPlatform/cloud-functions-emulator#78]
### Description

Initially my machine had Node v4.x, functions-emulator installed successfully but when I ran `functions start` it couldn't parse the start script it seems.

Once I installed node v6.x, I had to delete the previous folder in `/usr/lib/node_modules/@google-cloud` (not sure why NPM uninstall didn't work, but had to manually remove it) was able to get it `functions start` to run without errors.

### Expected Behavior

functions-emulator shouldn't have been successfully installed if Node v6.x is required.

### Actual Behavior

functions-emulator successfully installed but `functions start` couldn't start, had parse errors. (I think relating to ecmascript-6 style code? sorry I closed the terminal.)

### Steps to reproduce

1. node --version should be v4.x
2. `npm install -g @google-cloud/functions-emulator`
3. `functions start`

Thanks!

**Comment by jmdobry** [comment]
The Emulator's `package.json` file contains the proper "engines" clause, i.e.

```
"engines": {
  "node": ">=6.9.1"
},
```

so npm should have printed a warning printed when the Emulator was installed with Node v4. According to [npm "engines" docs](https://docs.npmjs.com/files/package.json#engines):

> Unless the user has set the **engine-strict** config flag, [the engines] field is advisory only and will produce warnings when your package is installed as a dependency.

So it sounds like if one wants the installation itself to fail when using an older Node.js version, one would need to set npm's engine-strict flag to true.
