### ISSUE TITLE
Add support for streaming logs

### ISSUE THREAD

**Issue by Alex-Mann** [GoogleCloudPlatform/cloud-functions-emulator#87]
For development purposes, it would be extremely helpful to have the ability to stream logs rather than having to `functions logs read` to check previous usage

**Comment by gerhardcit** [comment]
@Alex-Mann, you can simply tail -f the log file.

**Comment by Alex-Mann** [comment]
@gerhardcit any idea where that file is stored?

**Comment by gerhardcit** [comment]
@Alex-Mann 
`functions status` gives you the log file path.
